### ISSUE TITLE
Add new rules

### ISSUE THREAD

**Issue by sean-clayton** [smartprocure/eslint-config-smartprocure#24]
_**Extends `eslint:recommended`**_

### [eqeqeq](https://eslint.org/docs/4.0.0/rules/eqeqeq)
Proposed configuration: `["warning", "always"]`

Fixable: **Some**

```js
// Bad
let isOne = 1 == "1"

// Good
let isOne = 1 === "1"
```

### [arrow-body-style](https://eslint.org/docs/4.0.0/rules/arrow-body-style)
Proposed configuration: `["error", "as-needed"]`

Fixable: **Some**

```js
// Bad
let fun = () => {
  return {
    bob: 'burger'
  }
}

// Good
let fun = () => ({
  bob: 'burger'
})
```

### [prefer-spread](https://eslint.org/docs/4.0.0/rules/prefer-spread)
Proposed configuration: `"warn"`

Fixable: **Some**

```js
// Bad
bob.apply(null, burgers)
bob.apply(undefined, burgers)

// Good
foo(...burgers)
```

### [prefer-rest-params](https://eslint.org/docs/4.0.0/rules/prefer-rest-params)
Proposed configuration: `"warn"`

Fixable: **No**

```js
// Bad
function bob() {
  console.log(arguments);
}

// Good
function bob(...arguments) {
  console.log(arguments);
}
```

### [prefer-template](https://eslint.org/docs/4.0.0/rules/prefer-template)
Proposed configuration: `"error"`

Fixable: **Some**

```js
// Bad
str = "Hello, " + name + "!"

// Good
str = `Hello, ${name}!`
```

### [no-duplicate-imports](https://eslint.org/docs/4.0.0/rules/no-duplicate-imports)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
import React from 'react'
import { Component } from 'react'

// Good
import React, { Component } from 'react'
```

### [wrap-iife](https://eslint.org/docs/4.0.0/rules/wrap-iife)
Proposed configuration: `["error", "inside"]`

Fixable: **Some**

```js
// Bad
var x = function () { return { y: 1 }}()

// Good
var x = (function () { return { y: 1 }})()
```

### [no-console](https://eslint.org/docs/4.0.0/rules/no-console)
Proposed configuration: `"warn"`

Fixable: **No**

```js
// Bad
let a = thing => {
  console.log(thing)
  return { thing }
}

// Good
let a = thing => ({ thing })
```

### [no-unneeded-ternary](https://eslint.org/docs/4.0.0/rules/no-unneeded-ternary)
Proposed configuration: `"error"`

Fixable: **Some**

```js
// Bad
let isOne = a => a === 1 ? true : false
let aOrOne = a => a ? a : 1

// Good
let isOne = a => a === 1
let aOrOne = a => a || 1
```

### [require-await](https://eslint.org/docs/4.0.0/rules/require-await)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let fun = async a => async b => async c => {
  let thing = a(b)
  return thing(c)
}

// Good
let fun = async a => async b => async c => {
  let thing = await a(b)
  return thing(c)
}
```

### [one-var](https://eslint.org/docs/4.0.0/rules/one-var)
Proposed configuration: `["error", "never"]`

Fixable: **No**

```js
// Bad
let foo, bar, baz = 1

// Good
let foo
let bar
let baz = 1
```

### [no-empty-function](https://eslint.org/docs/4.0.0/rules/no-empty-function)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
function a() {}

let a = function() {}

let a = () => {}

// Good
function a(b) {
  b()
}

let a = function(b) {
  b()
}

let a = b => {
  b()
}
```

### [no-implicit-coercion](https://eslint.org/docs/4.0.0/rules/no-implicit-coercion)
Proposed configuration: `["error", {allow: ["!!", "~"]}]`

Fixable: **Some**

```js
// Bad
let n = 1 * "1"
let s = "" + 1
foo += ``

// Good
let b = !!"cheese"
let b = ~".burgers".indexOf(".")
let n = parseInt("2")
let s = 1.toString()
foo = String(foo)
```

### [no-return-assign](https://eslint.org/docs/4.0.0/rules/no-return-assign)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let a = b => c => b = c

// Good
let a = b => c => {
  b = c
}
```

### [no-return-await](https://eslint.org/docs/4.0.0/rules/no-return-await)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let async a => {
  return await a(1)
}

// Good
let async a => a(1)
```

### [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
class Thing extends React.Component {
  render() {
    return <div>Thing</div>
  }
}

// Good
let Thing = () => <div>Thing</div>
```

### [react/jsx-uses-vars](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
// Note that Hello isn't used
let Hello = require('./Hello')

// Good
let Hello = require('./Hello')

<Hello name='Bob the Builder'>
```

### [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
// Note that React is not used
let React = require('react');

// Good
// React is used because we're using JSX
let React = require('react')

let Hello = ({ name }) => <div>Hello, {name}</div>
```

### [react/react-in-jsx-scope](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let Hello = ({ name }) => <div>Hello, {name}</div>

// Good
let React = require('react')

let Hello = ({ name }) => <div>Hello, {name}</div>
```

### [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)
Proposed configuration: `"error"`

Fixable: **Yes**

```js
// Bad
let HelloBob = () => <Hello name="Bob"></Hello>

// Good
let HelloBob = () => <Hello name="Bob" />
let CoolTab = () => <Tab>Super cool!</Tab>
```

### [react/void-dom-elements-no-children](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/void-dom-elements-no-children.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let Stop = () => <img src="cool-image.jpeg">WAT</img>
let Wat = () => <br>PLZ STOP</br>

// Good
let Yay = () => <img src="cooler-image.jpeg" />
let Woo = () => <br />
```

### [lodash-fp/use-fp](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/use-fp.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
import _ from 'lodash'
import {map} from 'lodash'
import map from 'lodash/map'

// Good
import _ from 'lodash/fp'
import {map} from 'lodash/fp'
import map from 'lodah/fp/map'
```

### [lodash-fp/no-for-each](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-for-each.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
_.each(fn, [1, 2, 3])
_.forEach(fn, [1, 2, 3])
[1, 2, 3].forEach(fn)

// Good
_.map(fn, [1, 2, 3])
[1, 2, 3].map(fn)
```

### [lodash-fp/no-argumentless-calls](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-argumentless-calls.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
_.flow(
  _.map(fn1),
  _.filter(fn2),
  _.flatten() // <-- Boo
)(array)

// Good
_.flow(
  _.map(fn1),
  _.filter(fn2),
  _.flatten // <-- Yay
)(array)
```

### [lodash-fp/no-unused-result](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-unused-result.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
let arr = [1, 2, 3]
_.map(fn, arr) // <-- Does nothing

// Good
let arr = [1, 2, 3]
let newArr = _.map(fn, arr)
```

### [lodash-fp/prefer-flat-map](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/prefer-flat-map.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
_.flow(
  _.map(fn),
  _.flatten
)

// Good
_.flow(
  _.flatMap(fn)
)
```

### [lodash-fp/no-extraneous-iteratee-args](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-extraneous-iteratee-args.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
// i is never passed and therefore undefined
_.map((x, i) => x * i)

// Good
_.map(x => x * 2)
```

### [lodash-fp/no-single-composition](https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-single-composition.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
_.flow(
  _.map(fn)
)(x)

// Good
_.map(fn, x)
```

### [lodash/prop-shorthand](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/prop-shorthand.md)
Proposed configuration: `["error", "always"]`

Fixable: **No**

**Caveats:** I don't know if this works with lodash/fp

```js
// Bad
_.map(x => x.user.name, arr)

// Good
_.map('user.name', arr)
```

### [lodash/prefer-reject](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/prefer-reject.md)
Proposed configuration: `"error"`

Fixable: **No**

**Caveats:** I don't know if this works with lodash/fp

```js
// Bad
_.filter(x => !x.dontFilter, arr)

// Good
_.reject('dontFilter', arr)
```

### [import/no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md)
Proposed configuration: `["error", { commonjs: true }]`

Fixable: **No**

```js
// Bad
import thing from 'non/existant/path'
let thing = require('./non/existant/file')

// Good
import React from 'react'
let _ = require('lodash/fp')
let utils = require('../utils') // <-- Has to exist
```

### [mocha/no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
it.only('This is the only running test', () => {
  // ...
})

// Good
it('Is a normal test', () => {
  // ...
})
```

### [mocha/no-pending-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-pending-tests.md)
Proposed configuration: `"warn"`

Fixable: **No**

```js
// Bad
it('Is not a real test')

// Good
it('Is a real test', () => {
  // ...
})
```

### [mocha/no-skipped-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-skipped-tests.md)
Proposed configuration: `"error"`

Fixable: **Yes**

```js
// Bad
describe.skip('A skipped suite', () => {
  // ...No
})
xit('A skipped test', () => {
  // ...
})

// Good
describe('A normal suite', () => {
  // ...
})
it('A normal test', () => {
  // ...
})
```

### [jest/no-disabled-tests](https://github.com/facebook/jest/blob/master/packages/eslint-plugin-jest/docs/rules/no-disabled-tests.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
describe.skip('A skipped suite', () => {
  // ...No
})
xit('A skipped test', () => {
  // ...
})

// Good
describe('A normal suite', () => {
  // ...
})
it('A normal test', () => {
  // ...
})
```

### [jest/no-focused-tests](https://github.com/facebook/jest/blob/master/packages/eslint-plugin-jest/docs/rules/no-focused-tests.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
it.only('This is the only running test', () => {
  // ...
})
fit('Focused test', () => {
  // ...
})

// Good
it('Is a normal test', () => {
  // ...
})
```

### [jest/no-identical-title](https://github.com/facebook/jest/blob/master/packages/eslint-plugin-jest/docs/rules/no-identical-title.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
describe('A suite', () => {
  it('works', () => {})
  it('works', () => {})
})
describe('A suite', () => {
  it('does things', () => {})
  it('does things', () => {})
})

// Good
describe('A suite', () => {
  it('works', () => {})
  it('works even better', () => {})
})
describe('Another suite', () => {
  it('does things', () => {})
  it('does more things', () => {})
})
```

### [jest/valid-expect](https://github.com/facebook/jest/blob/master/packages/eslint-plugin-jest/docs/rules/valid-expect.md)
Proposed configuration: `"error"`

Fixable: **No**

```js
// Bad
expect()
expect(true)
expect(true).toBeTruthy

// Good
expect(true).toEqual(true)
expect(true).toBe(true)
expect(true).toBeTruthy()
```

**Comment by sean-clayton** [comment]
@smartprocure/development Please take a look at these proposed ESLint rules and _please_ give any concerns/feedback you have! You'll notice that we don't have any formatting rules--that's because [prettier](https://prettier.io/) will take care of that. We will implement these rules across all of our repos eventually, so your input is extremely valuable here.

**Comment by daedalus28** [comment]
Great work!
